encoding: UTF-8
timezone: Asia/Shanghai
url: https://fluffos.mud.ren

plugins:
  - jekyll-seo-tag                  # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap                  # https://github.com/jekyll/jekyll-sitemap/
